#!/bin/bash

# Script to do my current development run of restofus.
# Liable to change without notice.

# start afresh each run:
RECORDS=/tmp/records.json

rm -f $RECORDS

./restofus.py --records $RECORDS --import histon.csv
cp $RECORDS /tmp/0.json
./restofus.py --records $RECORDS --list-ringers
cp $RECORDS /tmp/1.json
# ./restofus.py --records $RECORDS --place "Cambridge Surprise Major"
# ./restofus.py --records $RECORDS --next
